ARG DOCKER_FROM=ubuntu:16.04

FROM ${DOCKER_FROM}

RUN apt-get -y update && apt-get install -y --no-install-recommends wget build-essential autoconf automake libtool \
    ca-certificates libz-dev libbz2-dev
